name: EXOS_TitleManagerAPI
version: '${project.version}'
main: vlavik.exos_titlemanagerapi.EXOS_TitleManagerAPI
api-version: '1.21'
commands:
  title-manager:
    description: "TitleManagerDebug"
depend:
  - packetevents